print(10 > 9)
print(10 == 9)
print(10 < 9)
x = "Hello"
y = 15
print(bool(x))
print(bool(y))
print(bool("abc"))
print(bool(123))
print(bool(["apple", "cherry", "banana"]))
print(bool([]))
print(bool({}))
print(bool(None))
print(bool(False))
print(bool(0))
print(bool(""))
print(bool(()))
print(bool({}))
print(bool(set()))
print(bool(dict()))
print(bool(tuple()))

